### ISSUE TITLE
Criar página de Contato

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/ObservaEPS#11]
## **Objetivo**

**Como** usuário
**Quero** acessar a página de contato
**Para** ver mapa de localização e falar com o ObservaEPS

## **Contexto**
Inserir form de contato conforme especificações fornecidas. Para o Mapa da página é preciso criar API de conexão com o e-mail do designlab

## **Escopo**

- [x] Adaptar API do Mapa
- [x] Ativar módulo do mapa
- [x] Formulário padrão com os campos:
- Nome*
- E-mail*
- Telefone
- Mensagem
- [x] inserir email do observatório
- [x] Inserir página no menu principal

## **Critérios de Aceitação**

**Dado que** acesso o site do Observatório
**Quando** entro na página contato
**Então** vejo o mapa de localização e o form de contato

**Comment by danielgula** [comment]
Até a data de hoje o servidor encontra-se fora do ar. Infra já foi alertada.

**Comment by danielgula** [comment]
@wforte88 conforme nosso entendimento solicito criar API de conexão com o e-mail do designlab para editarmos a página.

**Comment by wforte88** [comment]
**Mapa**
Javascript do Maps em conflito com o Divi. Foi inserido um iframe do mapa.

**Formulário de contato**
SMTP do SendGrid configurado e testado. E-mails entregues com sucesso.

**Captcha**
Removido captcha padrão do Divi e inserida API do reCaptcha v3.
