### ISSUE TITLE
Criar seção Biblioteca

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/ObservaEPS#12]
- [x] Verificar posts da categoria "Livros" e publicá-los como e-books
- [x] Criar template para a categoria e-books com o título "Biblioteca"
- [x] Criar página para Biblioteca
- [x] Inserir página no menu principal

**Comment by danielgula** [comment]
Até a data de hoje o servidor encontra-se fora do ar. Infra já foi alertada.

**Comment by danielgula** [comment]
Página criada em
https://observatorio.esp.ce.gov.br/biblioteca/
