### ISSUE TITLE
Ajustar home page

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/ObservaEPS#13]
- [x] Inserir links nos botões dos eixos para suas respectivas páginas
- [x] Inserir link para a Biblioteca #12
- [x] Inserir módulo portfólio com exibição dos últimos quatro projetos da Comunidade de Práticas
- [x] Verificar arquivos descartáveis
- [x] Revisar conteúdos enviados pelo ObservaESP

**Comment by danielgula** [comment]
Até a data de hoje o servidor encontra-se fora do ar. Infra já foi alertada.

**Comment by danielgula** [comment]
Home page criada.
Acesso
https://observatorio.esp.ce.gov.br/
